[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "problem_01"
path = "01/main.rs"

[[bin]]
name = "problem_02"
path = "02/main.rs"

[dependencies]
utils = { path = "./utils" }
